require('dotenv').config();

module.exports = {
    AZURE_OPENAI_CONFIG:{
        PARAMS_AZURE_OPENAI_DEPLOYMENT_VERSION: process.env.AZURE_OPENAI_DEPLOYMENT_VERSION,
        PARAMS_AZURE_OPENAI_DEPLOYMENT_NAME: process.env.AZURE_OPENAI_DEPLOYMENT_NAME,
        PARAMS_AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY,
        PARAMS_AZURE_OPENAI_ENDPOINT: process.env.AZURE_OPENAI_ENDPOINT,
    }
}
